Inserted calling of styling parameter in flexBox styling
jwstegemann/fritz2 pull request #407
Opened 2021-05-27 09:32 UTC by WestHuus

fixes #406

2021-05-31 14:27 UTC, jamowei requested changes
Do we need a `flexBox` here? When not it's would be nicer in my opinion to use a `div` instead and then no casting is needed to call the `styling()` function ;-)

2021-06-01 09:49 UTC, chausknecht requested changes
I think we should cancel this PR in favour of PR #361, which already solves the problem.

2021-06-01 09:49 UTC, chausknecht commented on components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
> +                div(baseClass = alertContentCss.name) {
Imho wrong! We need a ``StyleClass`` there and not a ``String`` - as the class also gets applied, I would definitly consider this as false correction!

2021-06-01 09:59 UTC, chausknecht commented on components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
> +                div(baseClass = alertContentCss.name) {
Ok, I revoke my comment!

This is for sure something off within our API... the overloaded factories have a different type of course, as the styling DSL (and therefor the type ``StyleClass``) is not available at core level!

2021-06-01 11:22 UTC, chausknecht commented
Obsolete, PR #361 covers this already!

2021-06-01 11:22 UTC, closed without merging