Improves key event handling
jwstegemann/fritz2 pull request #553
Opened 2021-11-29 16:52 UTC by chausknecht

- add some convenience methods to improve the event handling for `KeyboardEvent`s: ``keys()`` which accepts one, arbitrary or a set of `Key`s which should be handled. All events from other keys will be dropped, so that one can prevent default behaviour or stop bubbling explicitly only for the handled keys
- returns a pair of the key and the accompanied event, so that calling `stopPropagation` or accessing other properties of the event is still possible for the client.

## Attention
I intentionally did not provide those methods also for the `WindowListener<KeyboardEvent>` receiver! My reason is, that I cannot really imagine some use case where the stopping of bubbling would make sense at this point! So it should be sufficient to use the `key()` extension to get the `Key` without need to access the event further. Am I right here?

2021-12-02 16:04 UTC, jwstegemann submitted a review, later dismissed

2021-12-02 16:08 UTC, jamowei requested changes
Good idea, but I would suggest some more improvements.
- `key()` function should return a `Pair<Key, KeyboardEvent>` too (similartity)
- I would prefer same functions for `WindowListener` too

2021-12-02 16:10 UTC, jamowei submitted a review, later dismissed

2021-12-02 16:10 UTC, jamowei commented on core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
> +
Why you filter here? In my opinion this is not needed. Am I wrong?

2021-12-02 16:23 UTC, chausknecht commented
> Good idea, but I would suggest some more improvements.
> 
>     * `key()` function should return a `Pair<Key, KeyboardEvent>` too (similartity)
This would break API though! But I agree on the consistency aspect.
As we will break lots of API for the upcoming 0.14 release anyways and this is probably the last chance to do, I would vote for this proposal!

> 
>     * I would prefer same functions for `WindowListener` too

Have you read my discussion section in the PR comment? If so, please try to argue why this would make sense :-)

2021-12-14 14:37 UTC, jamowei submitted a review, later dismissed
Nice work! Perhaps you can define some tests for the different +-operator functions ;)

2021-12-14 14:40 UTC, chausknecht commented
Unit Tests should be definitly added before merging! I will complete this later on.

2021-12-20 16:24 UTC, chausknecht commented
Closed due to Github trouble (build process is stalled!).

See PR #556 instead.

2021-12-20 16:24 UTC, closed without merging